import { StyleSheet } from 'react-native';

/** Cyber Chat Widget palette (matches @kortex/ui). */
export const cyberTheme = {
  dark: {
    bg: '#020c18',
    panel: '#020c18',
    border: 'rgba(0,212,255,0.15)',
    text: '#ffffff',
    muted: 'rgba(255,255,255,0.55)',
    brand: '#00d4ff',
    status: '#34d399',
    userBubble: 'rgba(0,212,255,0.12)',
    userBubbleBorder: 'rgba(0,212,255,0.2)',
    assistantBubble: 'rgba(4,21,38,0.9)',
    assistantBubbleBorder: 'rgba(0,212,255,0.08)',
    inputBg: 'rgba(0,212,255,0.04)',
    inputBorder: 'rgba(0,212,255,0.15)',
    headerBg: '#041526',
  },
  light: {
    bg: '#f0f9ff',
    panel: '#ffffff',
    border: 'rgba(0,150,200,0.2)',
    text: '#0c1a24',
    muted: 'rgba(12,26,36,0.55)',
    brand: '#0099cc',
    status: '#10b981',
    userBubble: 'rgba(0,180,220,0.12)',
    userBubbleBorder: 'rgba(0,150,200,0.25)',
    assistantBubble: '#ffffff',
    assistantBubbleBorder: 'rgba(0,150,200,0.12)',
    inputBg: 'rgba(0,180,220,0.06)',
    inputBorder: 'rgba(0,150,200,0.2)',
    headerBg: '#e6f4ff',
  },
} as const;

export function createWidgetStyles(dark: boolean) {
  const t = dark ? cyberTheme.dark : cyberTheme.light;
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: t.bg },
    header: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
      backgroundColor: t.headerBg,
    },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    diamond: {
      width: 28,
      height: 28,
      transform: [{ rotate: '45deg' }],
      backgroundColor: t.brand,
      borderRadius: 4,
      opacity: 0.85,
    },
    title: {
      color: t.brand,
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    statusRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: t.status,
    },
    statusText: { color: t.muted, fontSize: 10 },
    subtitle: { color: t.muted, fontSize: 13, marginTop: 2 },
    list: { padding: 16, gap: 10 },
    welcome: { color: t.muted, fontSize: 15, lineHeight: 22 },
    messageRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, marginBottom: 10 },
    messageRowUser: { flexDirection: 'row-reverse' },
    avatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: 'rgba(0,212,255,0.15)',
      borderWidth: 1,
      borderColor: 'rgba(0,212,255,0.3)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: { color: t.brand, fontSize: 10, fontWeight: '700' },
    bubble: {
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      maxWidth: '78%',
      borderWidth: 1,
    },
    userBubble: {
      alignSelf: 'flex-end',
      backgroundColor: t.userBubble,
      borderColor: t.userBubbleBorder,
      borderBottomRightRadius: 4,
    },
    assistantBubble: {
      alignSelf: 'flex-start',
      backgroundColor: t.assistantBubble,
      borderColor: t.assistantBubbleBorder,
      borderBottomLeftRadius: 4,
    },
    bubbleText: { color: t.text, fontSize: 14, lineHeight: 21 },
    composer: {
      padding: 12,
      borderTopWidth: 1,
      borderTopColor: t.border,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: t.inputBorder,
      backgroundColor: t.inputBg,
    },
    input: {
      flex: 1,
      color: t.text,
      fontSize: 14,
      padding: 0,
    },
    sendButton: {
      width: 28,
      height: 28,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: 'rgba(0,212,255,0.3)',
      backgroundColor: 'rgba(0,212,255,0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendLabel: { color: t.brand, fontSize: 14, fontWeight: '700' },
    footer: { textAlign: 'center', fontSize: 10, marginTop: 6, color: t.muted },
    footerBrand: { color: t.brand },
    typingRow: { flexDirection: 'row', gap: 4, paddingVertical: 4 },
    typingDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: t.brand, opacity: 0.6 },
  });
}
